---
######################################33
# Cambiar "password123" por una pass real
######################################
- hosts: etg
  become: yes
  tasks:
    - name: Create_a_new_user_named_Bob  		   # Nombre de la tarea en nuestro playbook.
      user:   			# Este es el módulo que vamos a utilizar para creación de usuarios.  
        name: Bob   		# Nombre del usuario que vamos a crear.
        password: "{{ 'password123' | password_hash('sha512') }}"  # Esta línea es para establecer una contraseña segura.