---
- hosts: etg
  become: yes
  tasks:
    - name: Delete_Bob_user 		# Nombre de la tarea en nuestro playbook.
      user:   			# Este es el m贸dulo que vamos a utilizar para eliminar usuarios.  
        name: Bob     # Nombre del usuario que vamos a eliminar.
        state: absent  # Esta opci贸n indica al m贸dulo de Ansible que queremos eliminar al usuario en cuesti贸n.
